name: Playwright Automation with Allure Report

on:
  push:
    branches:
      - 'feature/master'

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:


      # Step 2: Set up Node.js environment
      - name: print hello world
        run : "Hello world"
