name: Playwright Automation with Allure Report

on:
  push:
    branches:
      - 'master'

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Ensure Playwright is installed globally
      - name: Install Playwright globally
        run: |
          chmod +x ./node_modules/.bin/playwright
          npx playwright install

      # Step 5: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Step 6: Generate Allure report
      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      # Step 7: Upload Allure report as artifact
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report